### PR TITLE
tidy error handling and logging

### LINKED ISSUE #56: API crashes on ENTER via stdin
loading the api then hitting the ENTER key produces the following.

```
cdieringer@Snapper-osx:~/node/nodeapi$ node dist/ -c
Running with COINS_ENV: development
Including New Relic agent
New Relic agent reporting disabled
Using default dbmap.json
Including COINSTAC routes
160115/112819.594, [log,startup], data: server running at: http://Snapper-osx:8800

/Users/cdieringer/node/nodeapi/dist/index.js:94
    server.plugins.logger.logError(['stderr'], data);
                         ^

TypeError: Cannot read property 'logError' of undefined
    at WriteStream.<anonymous> (/Users/cdieringer/node/nodeapi/dist/index.js:94:26)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at WriteStream.Readable.push (_
```

### PR DESCRIPTION
**Pull request by cdaringe**
#### asana

https://app.asana.com/0/10663154302695/90520988960982
# problem statement
- API request logging events should happen in the request lifecycle and be automatic (e.g. no manual logging in each route)
  - some manual logging occurs, which is loose and not widely implemented.  consequently, said logging doesn't offer the API any actionable value
  -  most requests are _not logged_ at all which is OK
  - because logging lifecycle hooks have not been added in, #67 was added to facilitate discussion on this
- `onPossiblyUncaughtExceptions` is no longer needed explicitly. `bluebird` promises tap onto `process.on('unhandledRejected')`. See [here](http://bluebirdjs.com/docs/api/error-management-configuration.html#global-rejection-events) for ref.
- error handlers are not commonized between `uncaughtException` and `unhandledRejection`
- some log activity is silenced because logger is not registered early enough
- redundant logging activity occurs per long design discussion in #44 
- #56
# solution
- primarily, address #44.  the other issues simply get bundled in as consequence
- close #56
- tidy index.js.  you will see a lot of RED. open it in just raw mode.  enjoy it's simplicity! :)
# discussion
- note the new content that shows up when you run the api.  that should have been present the whole time!
- note how we never error, log, then throw again.  this is **antipattern**.  throw, log, and crash.  OR, throw, recover, optionally log, continue
  - if you are _not_ going to recover, don't `try` wrap or `.catch` wrap.  no recovery means non-deterministic state, and the global error handlers which log and kill should kick in.

### CODE REVIEW

File: src/lib/utils/global-error-handler.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+    server.expose({
+        handleUncaught: (err) => {
+            server.log(
+                ['error'],
+                {
+                    message: err ? err.toString() : '(empty Error)',
+                    stack: err.stack
+                }
+            );
+            process.nextTick(() => process.exit(1));
```
Comment (cdaringe) [inline src/lib/utils/global-error-handler.js:15]: something is funky with the logging service.  even if the logger has initialized, calling `server.log(...)` does _not_ log immediately.  waiting for the event loop to clear does it.  would like to figure that out, but it's non-critical
